### ISSUE TITLE
database API

### ISSUE THREAD

**Issue by sinsinkun** [Dragontalker/Project2_fluxIM#21]
- [X] implement database on heroku/local
- [ ] ensure tables capture all necessary data
- [ ] create ORM functions to interface with database

**Comment by Dragontalker** [comment]
Completed `implement database on Heroku/local`.

**Comment by Dragontalker** [comment]
Decomposed this task into several minor tasks, see #25 #26 #27 #28 #29 for more details. Closing issue now.
