### ISSUE TITLE
Setup connection.js to work with database

### ISSUE THREAD

**Issue by sinsinkun** [Dragontalker/Project2_fluxIM#6]
Make sure the connection.js and orm.js work with both the heroku database AND the local database for testing purposes.

**Comment by Dragontalker** [comment]
Deployed JawsDB at Heroku @ 2021-03-02 11:10am and tested all schemas and seeds.

**Comment by Dragontalker** [comment]
`connection.js` and `orm.js` are both tested locally and on JawsDB. Closing issue now.
